#!/bin/bash

DIR=$1

if [ -z "$DIR" ]; then
	echo "install <dir> - install the files wherever you need them."
	echo "ERROR: Must supply install dir."
	exit 1;
fi
set -x

INSTALL='install -S'

FILES="clean_job make_job.py resubmit_job submit_jobs"

for ix in $FILES; do
	$INSTALL $ix $DIR
done
